- src/blas.rs
- src/device.rs
> Adding Send/Sync impls and impl launch with bigger tuples

- src/device.rs
- src/driver/mod.rs
- src/driver/result.rs
- src/lib.rs
> Renaming CudaError -> DriverError

- src/device.rs
> Adding TryFrom<CudaSlice<T>> for Vec<T>, and copy_into_async

- examples/launch-kernel.rs
- src/device.rs
- src/rng.rs
> Only allowing pass by value primitives

- src/device.rs
> Removing uses of std::vec!

- src/device.rs
block_dim has a maximum size of 1024, so for any size with > 1024, this would throw a cuda error.
Formula for grid dim taken from https://developer.nvidia.com/blog/cuda-refresher-cuda-programming-model/
> Fixing LaunchConfig::for_num_elems

- src/device.rs
> Adding feature to pass sub parts of slices into kernels

- src/cublas/bindgen.sh
- src/cublas/result.rs
- src/cublas/sys.rs
> Adding missing sys calls to cublas/sys.rs

- src/cublas/mod.rs
- src/cublas/safe.rs
- src/curand/mod.rs
- src/curand/safe.rs
- src/driver/mod.rs
- src/driver/safe.rs
- src/lib.rs
- src/nvrtc/mod.rs
- src/nvrtc/safe.rs
> Standardizing module organization. Moving safe apis to <module>/safe.rs

- src/driver/safe.rs
`CudaView` should have the same operations as `CudaSlice` (like slicing, copying, ...), though this would be a seperate PR. This closes #54, #55 (though a better name is required), #56 (partially) and #57.
> public alloc, ValidAsZeroBits for tuples, CudaSlice slicing with any range

- src/driver/safe.rs
> #52 Fixing LaunchConfig::for_num_elems docstring

- src/cublas/safe.rs
> #58 Add derive Debug to gemm config structs

- src/curand/safe.rs
- src/driver/safe.rs
- src/lib.rs
> Removing prelude

- Cargo.toml
- src/cublas/half.rs
- src/cublas/mod.rs
- src/cublas/result.rs
- src/cublas/safe.rs
- src/driver/safe.rs
- src/nvrtc/safe.rs
> f16 support

- src/driver/safe.rs
> Adding ability to copy between DevicePtr and DevicePtrMut

- src/driver/safe.rs
> Using default null stream instead of creating a stream

- src/driver/result.rs
> Adding event apis

- src/cublas/safe.rs
- src/curand/safe.rs
- src/driver/safe.rs
> Adding a free stream to concurrently free memory

- src/cublas/safe.rs
- src/driver/safe.rs
> Adding CudaStream & LaunchAsync::par_launch_async

- Cargo.toml
- build.rs
- src/driver/result.rs
- src/driver/safe/core.rs
- src/driver/safe/launch.rs
- src/driver/safe/ptx.rs
- src/lib.rs
- src/nvrtc/result.rs
- src/nvrtc/safe.rs
> Removing dep on find-cuda-helper. Moving no-std behind feature flag

- Cargo.toml
- build.rs
- src/lib.rs
This gives greater control over the parts of the library that are compiled
> Adds feature flags for each of the parts of cudarc

- Cargo.toml
- src/driver/safe/core.rs
> Adding transmute/transmute_mut

- src/driver/result.rs
- src/driver/safe/launch.rs
> Add inline tags to launches

- build.rs
> Add cudnn error msg

- src/driver/safe/alloc.rs
> Adds `CudaSlice::leak` and `CudaDevice::upgrade_device_ptr`

- src/driver/safe/alloc.rs
- src/driver/safe/core.rs
> Adds CudaDevice::null method & CudaSlice::device method

- src/driver/safe/core.rs
Resolves #98 
Is there anything more to this?
> Add ordinal to CudaDevice struct

- examples/07-build-workflow/build.rs
- examples/07-build-workflow/cuda/includes/my_struct.h
- examples/07-build-workflow/cuda/includes/wrapper.h
- examples/07-build-workflow/cuda/kernels/my_struct_kernel.cu
- examples/07-build-workflow/main.rs
> added complex build workflow example

- src/cudnn/result.rs
- src/cudnn/safe/conv.rs
- src/cudnn/safe/core.rs
> Fixing scalar parameters for f16

- src/cublas/result.rs
- src/cublas/safe.rs
- Adds gemm_ex and gemm_strided_batched_ex to cublas::result
- Uses the above two functions in Gemm<half::f16>
> Use compute type f32 for f16 matmul

- src/driver/safe/external_memory.rs
While trying to use the API I added in #152, I ran into usability issues.
Originally I had `MappedBuffer` hold a `PhantomData<&mut ExternalMemory>` which does make sense in principle, since it is essentially like a view, but it made it difficult to return `MappedBuffer` from functions.
By taking ownership of `ExternalMemory`, the drop order is still preserved, while making the API a bit easier to use in practice.
It does mean that you cannot map an `ExternalMemory` multiple times (before this you could `drop` the `MappedBuffer` to unmap), but I do not need that for my use-case, and in the future something like `MappedBuffer::unmap() -> ExternalMemory` could be added if it is needed.
This is a breaking change because it removes lifetime parameters and changes the function signatures of the …
> Improve external memory interface

- src/cublas/safe.rs
- src/cudnn/safe/core.rs
- src/curand/safe.rs
- src/driver/safe/alloc.rs
- src/driver/safe/core.rs
- src/driver/safe/external_memory.rs
- src/driver/safe/launch.rs
- src/driver/safe/profile.rs
- src/driver/safe/ptx.rs
- src/driver/safe/threading.rs
Resolves #160 
Resolves #161 
Resolves #165 
Resolves #108
> Calling bind_to_thread on all api calls

- src/driver/safe/launch.rs
> Fix typo in docs about for_num_elems of LaunchConfig

- src/cublaslt/safe.rs
Pretty big mistake on my side. The cuda objects were never destroyed.
> fix: fix cublaslt objects memory leak

- src/driver/safe/core.rs
> Replace unwrap with ? in CudaDevice::new()

- src/driver/safe/core.rs
> Add CudaDevice::new_with_stream

- src/lib.rs
redo of https://github.com/coreylowman/cudarc/pull/247
> add another windows lib_name workaround

- src/cublas/sys/mod.rs
- src/cublaslt/sys/mod.rs
- src/cudnn/sys/mod.rs
- src/curand/sys/mod.rs
- src/driver/sys/mod.rs
- src/lib.rs
- src/nccl/sys/mod.rs
- src/nvrtc/sys/mod.rs
> Improve panic message if dynamic loading failed.

- src/driver/safe/core.rs
**Problem statement**
As a Developer, when I read https://docs.rs/cudarc/latest/cudarc/driver/safe/struct.CudaStream.html, it is not clear how I can use cudarc to synchronize work across non-default CUDA streams.
**Solution**
In this PR, I added documentation for how to synchronize many non-default streams.
**Context**
In my previous PR https://github.com/coreylowman/cudarc/pull/254, I thought that CudaStream streams were thread-safe. 
My understanding was incorrect.
@coreylowman then kindly pointed that usually one achieves on-device concurrency by launching from the same host thread several CUDA kernels on several non-default non-blocking CUDA streams. So I read the CUDA documentation about streams to determine how to achieve this with cudarc.
cudarc uses the [CUDA events …
> Add documentation on how to synchronize non-default streams

- src/driver/result.rs
Partial progress for #258 
Unclear how to add this to safe API.
> Adding various functions to driver result api for managed memory

- src/cudnn/result.rs
> Fixing version check in cudnn for 11.4

- src/driver/result.rs
- src/driver/safe/launch.rs
> [Breaking][Waiting to Merge] Adds cooperative launch to LaunchAsync

- src/nccl/safe.rs
> Adds Comm::reduce_in_place and Comm::broadcast_in_place

- src/driver/safe/launch.rs
> Fix redundant bug in LaunchConfig::for_num_elems

- src/driver/result.rs
- src/driver/safe/alloc.rs
- src/driver/safe/core.rs
For creating pinned host memory.
Still need to write tests for this & figure out the correct flags.
Need to verify under what conditions creating a &[T] is valid for this.
> Adds PinnedHostSlice to support pinned memory copies

- src/curand/safe.rs
> [Breaking] Creating CudaRng requires CudaContext instead of CudaDevice

- src/curand/safe.rs
> CudaRng constructor now requires CudaStream

- src/cublaslt/safe.rs
- src/driver/safe/device_ptr.rs
- src/driver/safe/external_memory.rs
So you can call methods like alloc_zeros/etc on the returned stream
> Changing stream ref methods to return `&Arc<CudaStream>`

- build.rs
> Fixing missing symbols in static-linking

- src/driver/safe/core.rs
> Remove stream synchronizations with HostSlice

- src/driver/safe/core.rs
- src/driver/safe/external_memory.rs
- src/driver/safe/launch.rs
> Only doing event recording if multiple streams are created

- src/driver/safe/core.rs
Closes https://github.com/coreylowman/cudarc/issues/393
> Add `Send` & `Sync` for `PinnedHostSlice`

- bindings_generator/src/main.rs
- src/cublaslt/sys/mod.rs
- src/cusolver/sys/mod.rs
- src/cusparse/sys/mod.rs
- src/driver/sys/mod.rs
> Ignore cuCheckpoint api in bindings

- src/driver/result.rs
- src/driver/safe/launch.rs
- src/driver/safe/mod.rs
- src/driver/safe/unified_memory.rs
Resolves #258 
This is a complex set of APIs, so still working through this. Also need to add tests
> Adds UnifiedSlice - safe unified memory api

- .github/workflows/cargo-check.yaml
- Cargo.toml
- bindings_generator/src/main.rs
- build.rs
- src/cublas/sys/mod.rs
- src/cublaslt/sys/mod.rs
- src/curand/sys/mod.rs
- src/cusolver/sys/mod.rs
- src/cusparse/sys/mod.rs
- src/driver/sys/mod.rs
- src/nvrtc/sys/mod.rs
- src/runtime/sys/mod.rs
> Add support for cuda 12.9

- bindings_generator/src/main.rs
- src/runtime/sys/mod.rs
> filter cudaDeviceGetNvSciSyncAttributes

- build.rs
> Adding `CUDARC_CUDA_VERSION` override to build.rs

- build.rs
Resolves #416 
Previously the only thing we used the toolkit root for was to add it to `rustc-link-search`. We didn't actually use `cuda.h` for anything other than to just verify the correct directory was found.
Now we just add all the root candidates to the link search, as long as they are actual directories that exist.
This will still fail later in the build process if the correct libs are not found
> No longer search for cuda.h header in build.rs

- build.rs
> Add newer versions of cudnn to link searches
