coreylowman/cudarc

- examples/simple-matmul.rs
- src/device.rs
- src/lib.rs
Addresses #33 
This PR changes IntoKernelParam by taking a `&self` reference instead of `self`. It also adds a default implementation for the method.
Also renaming `IntoKernelParam` to `AsKernelParam` to reflect the change.
> Reworking IntoKernelParam -> AsKernelParam

- src/driver/safe.rs
This change is needed to implement https://github.com/coreylowman/dfdx/issues/306 because the output of comparison operations is a boolean, and for CUDA we want to initialize the output tensor beforehand.
I believe it is sound, as according to the links below, `0` is guaranteed to be interpreted as `false` in both Rust and C++.
- https://doc.rust-lang.org/reference/types/boolean.html
- https://stackoverflow.com/questions/19351483/how-is-a-bool-represented-in-memory
> Implement ValidAsZeroBits for bool

- src/curand/safe.rs
- src/driver/safe/alloc.rs
- src/driver/safe/core.rs
- src/driver/safe/launch.rs
- src/driver/safe/mod.rs
Resolves #70 
Currently its possible to allocate/send types that aren't actually valid cuda types. This PR reworks AsKernelParam to the more general DeviceRepr, which is used in place of AsKernelParam.
Addtionally, things that allocate CudaSlice have `T: DeviceRepr` now
> Adding DeviceRepr, removing AsKernelParam

- examples/01-allocate.rs
- examples/02-copy.rs
- examples/launch-kernel.rs
- examples/simple-matmul.rs
- src/cublas/safe.rs
- src/curand/safe.rs
- src/driver/safe/alloc.rs
- src/driver/safe/build.rs
- src/driver/safe/core.rs
- src/driver/safe/launch.rs
- src/driver/safe/mod.rs
resolves #55 
New names for things:
- alloc
- alloc_zeros
- memset_zeros
- launch
- launch_on_stream
- dtod_copy
- htod_copy
- htod_copy_into
- htod_sync_copy
- htod_sync_copy_into
- dtoh_sync_copy
- dtoh_sync_copy_into
- sync_reclaim
> Consistent & clear naming convention

- src/driver/safe/core.rs
- src/driver/safe/mod.rs
I believe this may be the case of the memory leak here: https://github.com/coreylowman/dfdx/issues/523
When I run a simple benchmark with using the free stream, the memory use becomes 100% of the GPU. If I remove the free stream, the memory usage only gets to about 30%, indicating that the gpu wasn't freeing memory.
> Reverting free stream, putting free_async calls on default stream

- examples/04-streams.rs
- src/driver/safe/core.rs
- src/driver/safe/launch.rs
- CudaDevice::wait_for now accepts reference to stream, so you don't have to destroy it.
- Adds CudaStream::wait_for_default so you can synchronize a stream with CudaDevice's stream.
This allows you to keep a single stream alongside CudaDevice to synchronize with, so you don't have to keep creating/destroying
> More sound CudaStream

- Cargo.toml
- build.rs
When building binaries with cuda, the dependency on the libs is super large.
Biggest culprit is cublasLt which is 485Mb on its own.
Using static linking, shrinks everything into the binary which becomes ~130Mo (after stripping) in my case.
It also makes cublas loading much faster.
> Static linking (with feature flag).

- src/driver/safe/core.rs
- src/driver/safe/ptx.rs
To support things like determining module name based on parameters. E.g. `conv2d_<width>_<height>`, where width/height are known at runtime, and therefore you don't have a `&'static str`
> Support runtime names of modules

- build.rs
> Add `lib` as a library candidate in build.rs

- src/cudnn/result.rs
- src/cudnn/safe/conv.rs
> Adds Conv2dDescriptor::set_group_count

- src/driver/safe/core.rs
- Adds `CudaDevice::cu_primary_context()`
- Adds `CudaDevice::cu_device()`
- Adds `CudaDevice::cu_stream()`
> Adding methods to get reference to internal sys handles of CudaDevice

- src/driver/result.rs
- src/driver/safe/external_memory.rs
- src/driver/safe/mod.rs
- Add unsafe functions to `crate::driver::result` in a new `external_memory` module which wrap raw bindings for interacting with external memory.
- Add safe(?) wrapper in the form of two new types `ExternalMemory` and `MappedBuffer` which abstract away interactions with external memory and to manage cleanup on drop.
I did not add any tests because I don't yet know how to get a valid file descriptor using only CUDA. At least I confirmed that this interface works with a file descriptor exported from Vulkan (via `vulkano` crate). The code exists in my repo https://github.com/ViliamVadocz/nvidia-video-codec-sdk on the `cudarc-external-memory` branch (very experimental and unorganized).
> Add functions to interact with external memory

- .gitignore
- src/driver/result.rs
- src/driver/safe/core.rs
The .rustfmt.toml ensures formatting is respected when inside a Cargo workspace that might have different formatting.
> Adds an attribute method for device and a .rustfmt.toml

- src/driver/result.rs
Some questions: 
How do you plan to return multiple values (cuOccupancyMaxPotentialBlockSize)? 
How would the safe API look like?
> WIP: Add occupancy to driver::result

- src/driver/safe/launch.rs
- src/driver/safe/mod.rs
- src/driver/safe/profile.rs
In some context this might be easier to use than calling `profiler_stop()` explicitly.
> Adding RAII version for the profiler.

- src/cublas/safe.rs
(first thanks for this neat crate, it's very helpful)
This PR adds the `Gemm` trait for `bf16` so that cublas can easily be used on this type, the code is very similar to the `f16` variant but with the cuda types adapted to `bf16`.
The gemm `f16` test has also been adapted to test this variant too, all this being behind the `f16` feature flag.
> Implement Gemm<bf16> for CudaBlas.

- src/driver/safe/alloc.rs
- These tests fail on single GPU machine (which I guess is most devs setups).
- This adds a simple device count check before running the test.
Alternatives:
- Use a feature flag (seems overengineered).
- Add `#[ignore]` (but then we're discarding those tests basically).
- Use and environment variable.
I feel like the proposed approach is simple enough we actually get the testing run on valid platforms.
If there's a need for much more multi GPU tests, then maybe the solution should evolve.
> Making the tests pass on single GPU platforms.

- src/cublas/safe.rs
- src/driver/safe/core.rs
Hello,
Here is a draft pull request for #102. These are only the minimum changes (no docs, default parameters, etc..)
> Minimum changes for occupancy API

- src/curand/result.rs
- src/curand/safe.rs
Setting the seed with curandSetPseudoRandomGeneratorSeed() initializes the state of the PRNG but does not restart the sequence.
Per the docs curandSetGeneratorOffset() can be used to skip ahead in the random sequence such that "multiple runs of the same program to continue generating results from the same sequence without overlap". It may also be desirable to reset the offset back to zero (or another index) to reproduce a prior result.
The change simply adds set_offset to expose access to curandSetGeneratorOffset().
> Add set_offset so that curandSetGeneratorOffset() can be called.

- src/driver/safe/launch.rs
I'm working with runtime-generated kernels that can take in varying amounts of inputs. The number of inputs isn't known at compile time, so I build up a vec of c_void pointers to the inputs. This didn't work with launch, so I implemented LaunchAsync trait for arrays of pointers.
> Implemented LaunchAsync for raw ptr arrays

- .github/workflows/cargo-check.yaml
- .github/workflows/cargo-clippy.yaml
- Cargo.toml
- build.rs
- src/cublas/sys/mod.rs
- src/cublaslt/sys/mod.rs
- src/cudnn/result.rs
- src/cudnn/sys/mod.rs
- src/curand/sys/mod.rs
- src/driver/safe/core.rs
- src/driver/sys/mod.rs
- src/nccl/sys/mod.rs
- src/nvrtc/sys/mod.rs
Changes:
1. Rename `cuda_auto_version` -> `cuda-version-from-build-system`
2. Change underscores to hyphens for all cuda versions (e.g. `cuda_12030` -> `cuda-12030`)
3. Remove `cuda-version-from-build-system` as a default feature
4. Compiler error in build script if no version feature is specified.
This means users will get a compile error until they either enable feature `cuda-version-from-build-system` or one of the other version features.
Reasoning: Making users specify explicitly what version they expect to compile for should cut down on errors related to that.
> Rework cuda versioning features - Users must always specify a version feature instead of having default behavior.

- build.rs
- src/cublas/sys/mod.rs
- src/cublaslt/sys/mod.rs
- src/cudnn/sys/mod.rs
- src/curand/sys/mod.rs
- src/driver/sys/mod.rs
- src/lib.rs
- src/nccl/sys/mod.rs
- src/nvrtc/sys/mod.rs
Resolves #219 
Resolves #232 
Searching list of candidate library names when dynamic loading now.
List may not be exhaustive - so we may need to add more options in the future. I've seen some lib names that different on the same system (e.g. there's cublasLt64_12.dll and nvrtc64_10.dll on the same system).
> Adding fallback lib name options for dynamic loading

- build.rs
Resolve #239 
Swapping to extracting cuda toolkit version by running `nvcc --version` and parsing the output. The previous method had a lot of shortcomings, and nvcc is pretty standard way to get the cuda toolkit version.
For more information on this see https://stackoverflow.com/questions/53422407/different-cuda-versions-shown-by-nvcc-and-nvidia-smi
> Using nvcc to get cuda toolkit version instead of cuda.h

- .github/workflows/cargo-check.yaml
- .github/workflows/cargo-clippy.yaml
- src/cudnn/safe/mod.rs
- src/driver/safe/alloc.rs
- src/driver/safe/core.rs
- src/nccl/result.rs
- src/nccl/safe.rs
This is an attempt to address #233.
Since this is code that touches some aspects of the lifetimes of `CudaView` and `CudaViewMut`, this could use some extra scrutiny to check if the safety invariants of the involved types are still ok. 
I removed the `root` field of both `CudaView` and `CudaViewMut`, since it's only purpose was AFAIK, to keep track of the lifetimes of the respective structs. I have moved this into a `PhantomData` which should serve the same purpose.
Furthermore, I have now added the `split_at_mut` methods to `CudaSlice` and `CudaViewMut`, which mimic the behavior of `split_at_mut` of the standard library.
The old method of storing a `&mut` to the cuda device pointer does not work for splitting, since it would mean that there exist two mutable references to the same value …
> Add `CudaSlice::split_at_mut` and `CudaViewMut::split_at_mut`

- src/driver/result.rs
- src/driver/safe/core.rs
> Add `CudaDevice::name()` and `result::device::get_name()`

- src/driver/result.rs
Mentioned in #265 
Also linking to https://github.com/EricLBuehler/mistral.rs/issues/395#issuecomment-2189994656
> Handling self.error_string() failing in Debug for DriverError

- src/driver/result.rs
- src/nccl/result.rs
**Problem**
Both `cuMemAdvise_v2` and `cuMemPrefetchAsync_v2` were added in CUDA toolkit 12.2, but cudarc tries to use them for all CUDA toolkit versions.
**GitHub issue**
https://github.com/coreylowman/cudarc/issues/269
**Analysis**
Using the NVIDIA documentation, I could not find in which CUDA toolkit version the functions `cuMemAdvise_v2` and `cuMemPrefetchAsync_v2` were added.
I found the information on the AMD web site here: https://rocm.docs.amd.com/projects/HIPIFY/en/latest/tables/CUDA_Driver_API_functions_supported_by_HIP.html
According to this web page, both `cuMemAdvise_v2` and `cuMemPrefetchAsync_v2` were added in CUDA toolkit 12.2.
**Solution**
Use these functions only with CUDA toolkit 12.2 or later.
**NVIDIA GPU model**
```
sebhtml@legion:~/projects/cudarc$ nvidia-smi
Sat …
```
> Fix compiler error due to unavailability of some CUDA methods

- src/cublaslt/safe.rs
- src/driver/mod.rs
- src/driver/result.rs
- src/driver/safe/core.rs
- src/driver/safe/launch.rs
- src/nccl/safe.rs
This PR allows the NCCL communication operations to operate on `CudaView` and `CudaViewMut` as well. I also added a small test to show this works as intended by copying the old one.
> [breaking][waiting to merge] feat: allow NCCL comm type to operate on views as well

- src/cublas/safe.rs
Adds two safe methods to `CudaBlas`:
- `set_pointer_mode`: is this function https://docs.nvidia.com/cuda/cublas/#cublassetpointermode
- `get_pointer_mode`: is this function https://docs.nvidia.com/cuda/cublas/#cublasgetpointermode
There is also a test to ensure it works as expected.
This is important to have, as some cuBLAS functions require the `CUBLAS_POINTER_MODE_DEVICE`
to be set when attempting to pass in device memory as a result buffer.
If the `cublasPointerMode_t` is not changed from the default `CUBLAS_POINTER_MODE_HOST` in that case,
then the function panics with `SIGSEGV: invalid memory reference`.
I discovered that mechanism while trying to use the `cublas<t>asum()` function (<https://docs.nvidia.com/cuda/cublas/index.html#cublas-t-asum>)
Here is an example that illustrates …
> Add safe methods `set_pointer_mode` and `get_pointer_mode`

- src/cudnn/result.rs
- src/cudnn/safe/activation.rs
- src/cudnn/safe/conv.rs
- src/cudnn/safe/mod.rs
- src/cudnn/safe/pooling.rs
#178 
* [pooling](https://docs.nvidia.com/deeplearning/cudnn/latest/api/cudnn-ops-library.html?highlight=cudnnsetpoolingnddescriptor#cudnnpoolingforward) 
* [activation](https://docs.nvidia.com/deeplearning/cudnn/latest/api/cudnn-ops-library.html?highlight=cudnnsetpoolingnddescriptor#cudnnactivationforward)
* [conv-bias-activation](https://docs.nvidia.com/deeplearning/cudnn/latest/api/cudnn-cnn-library.html?highlight=cudnnconvolutionbiasactivationforward#cudnnconvolutionbiasactivationforward)
> Add more cudnn operations

- src/cudnn/result.rs
- src/cudnn/safe/activation.rs
- src/cudnn/safe/conv.rs
- src/cudnn/safe/pooling.rs
- src/cudnn/safe/reduce.rs
- src/nccl/safe.rs
- src/runtime/result.rs
The following functions should've been listed as unsafe but were not:
- `cudnn::result::set_pooling_descriptor`
- `cudnn::result::pooling_forward`
- `cudnn::result::set_activation_descriptor`
- `cudnn::result::activation_forward`
This has no impact on the safe API
> [Breaking - cudnn::result apis] Adds missing unsafe fn declarations in cudnn::result

- src/nccl/safe.rs
> [Breaking] `&Option<T>` -> `Option<&T>` in nccl broadcast. Add Option argument to nccl reduce.

- src/driver/safe/mod.rs
`PinnedHostSlice` was missing a pub use.
> Export PinnedHostSlice as pub use

- examples/01-allocate.rs
- examples/02-copy.rs
- examples/03-launch-kernel.rs
- examples/04-streams.rs
- examples/05-device-repr.rs
- examples/06-threading.rs
- examples/matmul-kernel.rs
- src/cublas/safe.rs
- src/cublaslt/safe.rs
- src/cudnn/safe/core.rs
- src/curand/safe.rs
- src/driver/mod.rs
- src/driver/result.rs
- src/driver/safe/alloc.rs
- src/driver/safe/core.rs
- src/driver/safe/device_ptr.rs
- src/driver/safe/external_memory.rs
- src/driver/safe/host_slice.rs
- src/driver/safe/launch.rs
- src/driver/safe/mod.rs
- src/driver/safe/ptx.rs
- src/driver/safe/threading.rs
- src/nccl/result.rs
- src/nccl/safe.rs
Follow up to #335 
Resolves #340
Resolves #314 
- Add new methods to `trait DeviceSlice`
- Remove `trait LaunchAsync`, see sections below for new launch API.
- Remove implementations of `DeviceRepr` for `&CudaSlice`, `&mut CudaSlice`, `&CudaView`, `&mut CudaViewMut`. These have been replaced with implementations of `AsLaunchParam`.
- Remove `CudaSlice::device()`. Replaced with `CudaSlice::ordinal()` and `CudaSlice::context()`
- `CudaFunction::occupancy_max_active_clusters()` and `CudaFunction::occupancy_max_potential_cluster_size()` now require a `&CudaStream` argument
- Remove field `CudaStream.stream`. Replaced with `CudaStream.cu_stream()`
Currently there's no way to have an existing CudaDevice use a separate CudaStream for things like allocation/memcpy/memset operations. There's …
> [Breaking] Add CudaContext, CudaEvent. Refactor CudaStream & launching

- src/driver/safe/core.rs
LaunchConfig already has a field for this value, so we just use that.
> [Breaking] Remove extra shared mem arg in occupancy functions

- examples/02-copy.rs
- src/nccl/safe.rs
Follow up to #341 
This is for two main reasons:
1. To align all the libraries to utilize the same API (all of them are moving to construction with streams)
2. To make it clear what stream the Comm object operates on
3. To enable Comm to operate on a separate stream
4. To increase the soundness of multi stream operations with slices/views.
This PR adds ptr.block_for_read/write and ptr.record_read/write calls in all the NCCL apis.
> [Breaking] nccl::Comm now constructed with CudaStream

- examples/01-allocate.rs
- src/cublas/safe.rs
Follow up to https://github.com/coreylowman/cudarc/pull/341
- [Breaking] CudaBlas::new() now requires `Arc<CudaStream>` instead of `Arc<CudaDevice>`
- [Breaking] CudaBlas::set_stream() arguments changed to `set_stream(&mut self, stream: Arc<CudaStream>)`
This is for two main reasons:
- To align all the libraries to utilize the same API (all of them are moving to construction with streams)
- To make it clear what stream the CudaBlas object operates on
- To enable CudaBlas to operate on a separate stream
- To increase the soundness of multi stream operations with slices/views.
This PR adds ptr.block_for_read/write and ptr.record_read/write calls in all the cublas apis.
> [Breaking] CudaBlas constructor requires CudaStream

- src/cublaslt/safe.rs
- [Breaking] `CudaBlasLT::new()` now requires `Arc<CudaStream>` instead of `Arc<CudaDevice>`
- [Breaking] `trait MatmulShared::stream()` now returns `&CudaStream` instead of `&CUstream`
> [Breaking] CudaBlasLT constructor requires CudaStream

- src/cudnn/safe/activation.rs
- src/cudnn/safe/conv.rs
- src/cudnn/safe/core.rs
- src/cudnn/safe/mod.rs
- src/cudnn/safe/pooling.rs
- src/cudnn/safe/reduce.rs
- [Breaking] Cudnn::new() now requires `Arc<CudaStream>` instead of `Arc<CudaDevice>`
- [Breaking] Cudnn::set_stream() now looks like `set_stream(&mut self, stream: Arc<CudaStream>)`
> [Breaking] Cudnn now requires CUdaStream in constructor

- examples/02-copy.rs
- examples/03-launch-kernel.rs
- examples/04-streams.rs
- examples/05-device-repr.rs
- examples/06-threading.rs
- examples/matmul-kernel.rs
- src/driver/safe/alloc.rs
- src/driver/safe/core.rs
- src/driver/safe/launch.rs
- src/driver/safe/profile.rs
- src/driver/safe/ptx.rs
You can use `CudaModule::load_function` now instead.
> CudaModule doesn't load CudaFunction on creation anymore

- Cargo.toml
- src/driver/safe/host_slice.rs
Since we've removed `CudaDevice` (#351), and we no longer store modules in `RwLock<BTreeMap<String, CudaModule>>`, we no longer need this dependency on spin.
This was only used in no-std environment
> Remove dependency on `spin` for no-std builds

- src/driver/safe/core.rs
- [Breaking] `CudaView::transmute()` now keeps the same lifetime as the source view
- [Breaking] `CudaViewMut::transmute()` now keeps the same lifetime as the source view
- [Breaking] `CudaViewMut::transmute_mut()` now keeps the same lifetime as the source view
- Add `CudaSlice::split_at()` and `CudaSlice::try_split_at()`
> [Breaking] View clones now maintain lifetimes instead of creating new lifetimes

- src/cublas/safe.rs
- src/cublaslt/safe.rs
- src/cudnn/safe/activation.rs
- src/cudnn/safe/conv.rs
- src/cudnn/safe/pooling.rs
- src/cudnn/safe/reduce.rs
- src/curand/safe.rs
- src/driver/safe/core.rs
- src/driver/safe/external_memory.rs
- src/nccl/safe.rs
- [Breaking] DevicePtr::device_ptr() now returns `sys::CUdeviceptr` instead of a reference
- [Breaking] DevicePtrMut::device_ptr_mut() now returns `sys::CUdeviceptr` instead of a reference
- [Breaking] DevicePtr::device_ptr() now requires a stream reference as input to enforce synchronization on access
- [Breaking] DevicePtrMut::device_ptr_mut() now requires a stream reference as input to enforce synchronization on access
I'm looking into how to automatically do the event record that we also require on drop, but for now we are keeping it as just call after the work completes.
> [Breaking] Require stream synchronization to access device ptrs

- src/cublas/safe.rs
- src/cublaslt/safe.rs
- src/cudnn/safe/activation.rs
- src/cudnn/safe/conv.rs
- src/cudnn/safe/pooling.rs
- src/cudnn/safe/reduce.rs
- src/curand/safe.rs
- src/driver/safe/core.rs
- src/driver/safe/external_memory.rs
- src/driver/safe/launch.rs
- src/driver/safe/mod.rs
- src/nccl/safe.rs
This is to *as thoroughly as possible* make it hard to not record slice read/write events on the stream. Previously as you can see by the diff, authors who used device_ptr/device_ptr_mut had to manually call record_read/record_write.
I actually forgot some of the places while updating the code.
This PR adds an additional value to the result of device_ptr/device_ptr_mut. When that value is dropped, the corresponding event calls `event.record(stream)`.
After this PR, callees of device_ptr/device_ptr_mut will not need to worry about knowing about stream synchronization, it will automatically occur.
> Adds `SyncOnDrop` & DevicePtr/Mut now return `(CUdeviceptr, SyncOnDrop)`

- README.md
- examples/03-launch-kernel.rs
- examples/04-streams.rs
- examples/05-device-repr.rs
- examples/06-threading.rs
- examples/matmul-kernel.rs
- src/driver/safe/core.rs
- src/driver/safe/launch.rs
Resolves #361 
So this issue was caused by lifetime issues when using `--release`. The old implementation of `PushKernelArg` accepted owned values (`--release` was not tested during development), and relied on `#[inline(always)]` to attempt to ensure the lifetime of the reference was valid. I suspect this used worked in the old tuple implementation for kernel args because the lifetime implementation for tuples is different from raw scalars.
This PR changes the implementation to explicitly annotate the reference it now takes outlines the `LaunchBuilder` struct.
> PushKernelArg for scalar now takes reference

- src/driver/safe/launch.rs
The LHS has units of ms, but the RHS looks like it may have been intended to be 20% rather than an absolute tolerance of 0.2 ms. Without this change, I get test failures like this:
```
thread 'driver::safe::launch::tests::test_par_launch' panicked at src/driver/safe/launch.rs:670:9:
par=147.41606 dbl=295.22842
```
> driver/safe test: fix 20% relative tolerance instead of absolute

- src/driver/safe/core.rs
There may be slightly less overhead with this call, and it's called very frequently. I remember when we first added bind_to_thread, it didn't noticeably affect throughput, but this version should be the same or faster.
> Check `ctx::get_current()` before calling `ctx::set_current()`

- src/cublaslt/safe.rs
This (breaking) PR adds `transc` to `MatmulConfig`. While it can be useful to have this exposed, this is a breaking change for what is likely a relatively narrow use case. Please let me know if this makes sense!
> Expose cublaslt transc

- src/cublas/safe.rs
- src/curand/safe.rs
- src/driver/safe/core.rs
- src/driver/safe/external_memory.rs
- src/driver/safe/graph.rs
- src/driver/safe/launch.rs
Resolves #277 
Resolves #396
Adds `AtomicU32` into `CudaContext` which can track errors that occur in functions that cannot return a Result, like `Drop::drop()`.
These errors can be recorded with new method `CudaContext::record_err()`.
The driver code now also calls `CudaContext::check_err()` at the beginning of functions which return `Result`, which will reset error state to empty and return the error if there is one.
>  Save errors in Drop impls instead of .unwrap()

- src/nvrtc/result.rs
- src/nvrtc/safe.rs
It seems like in recent nvrtc versions (at least in 12.8), the program source code and name are not copied in nvrtcCreateProgram, but instead kept as a reference. Previously, cudarc would create a temporary CString which was dropped before destroying the nvrtcProgram. This led to various miscompilations and crashes in nvrtc when compiling many programs in parallel. This commit fixes the problem by keeping the corresponding CStrings alive for the lifetime of the nvrtcProgram.
> Fix apparent use-after-free in nvrtc.

- src/cudnn/result.rs
- src/cudnn/safe/mod.rs
- src/cudnn/safe/softmax.rs
This PR introduces a safe API for softmax operations (cudnnSoftmaxForward).
cuDNN does not provide a dedicated descriptor for softmax, unlike operations such as activation or convolution. To keep the API consistent, this implementation introduces a Softmax<T> type and a corresponding Cudnn::create_softmax() constructor, following the same design approach used for operations like ActivationDescriptor.
> Feat: add softmax support

- Cargo.toml
- src/driver/safe/core.rs
Add dependency and `DeviceRepr` impls for fp8. 
@EricLBuehler currently has these behind a feature in the float8 repo but to avoid circular dependencies this should mirror how half is used in cudarc.
> fp8 and fp4 support

- src/cudnn/mod.rs
Bring back cuDNN support for cuda13 since according to [cuDNN docs](https://docs.nvidia.com/deeplearning/cudnn/backend/latest/reference/support-matrix.html) it is supported now
> Remove compile error for unsupported CUDA 13.0 in cudnn module
